
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from models import products,recipts,session
import inventory_dashboard
class Ui_Form(object):
    def __init__(self) -> None:
        self.parent_widget = QtWidgets.QWidget()
    def addProduct(self):
        if self.name.text() == '' or self.price.text() == '' or self.units.text() == '' or self.price.text().isalpha():
            QMessageBox.critical(self.parent_widget,'Error inserting values',"Null and incorrect values cannot be entered to the database")
        else: 
            product_available = session.query(products).filter_by(name=self.name.text().upper()).first()
            if product_available:
                QMessageBox.critical(self.parent_widget,'Error posting product','The product you are trying to enter into the database already exists')
            else:
                new_product = products(name=self.name.text().upper(),units=self.units.text(),price=float(self.price.text()),category=self.category.currentText())
                session.add(new_product)
                session.commit()
                QMessageBox.information(self.parent_widget,'success','The item was successfully added to the database')
    def viewProducts(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = inventory_dashboard.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        Form.setMaximumSize(1000,800)
        Form.setMinimumSize(1000,800)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1001, 111))
        self.widget.setStyleSheet("background-color: rgb(8, 160, 75);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(400, 10, 341, 51))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1001, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(390, 130, 251, 31))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 210, 91, 31))
        self.label_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(400, 199, 501, 61))
        self.name.setObjectName("name")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(110, 311, 91, 31))
        self.label_4.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.units = QtWidgets.QLineEdit(Form)
        self.units.setGeometry(QtCore.QRect(400, 300, 501, 61))
        self.units.setObjectName("units")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(110, 421, 271, 31))
        self.label_5.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(400, 410, 501, 61))
        self.price.setText("")
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(110, 571, 91, 31))
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.category = QtWidgets.QComboBox(Form)
        self.category.setGeometry(QtCore.QRect(400, 561, 501, 51))
        self.category.setObjectName("category")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(-10, 770, 1011, 31))
        self.widget_2.setStyleSheet("background-color: rgb(100, 233, 134);")
        self.widget_2.setObjectName("widget_2")
        self.add_item = QtWidgets.QPushButton(Form)
        self.add_item.setGeometry(QtCore.QRect(40, 660, 271, 81))
        self.add_item.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.add_item.setObjectName("add_item")
        self.add_item.clicked.connect(self.addProduct)
        self.view_inventory = QtWidgets.QPushButton(Form)
        self.view_inventory.setGeometry(QtCore.QRect(410, 660, 271, 81))
        self.view_inventory.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.view_inventory.setObjectName("view_inventory")
        self.view_inventory.clicked.connect(self.viewProducts)
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(770, 660, 161, 81))
        self.exit.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ADD PRODUCT"))
        self.label_2.setText(_translate("Form", "Fill In The Fields Below"))
        self.label_3.setText(_translate("Form", "Name:"))
        self.label_4.setText(_translate("Form", "Units:"))
        self.label_5.setText(_translate("Form", "Price per unit(KSH):"))
        self.label_6.setText(_translate("Form", "Category:"))
        self.category.setItemText(0, _translate("Form", "Grocery"))
        self.category.setItemText(1, _translate("Form", "Stationary"))
        self.category.setItemText(2, _translate("Form", "Food Stuff"))
        self.category.setItemText(3, _translate("Form", "Hardware"))
        self.category.setItemText(4, _translate("Form", "Software"))
        self.add_item.setText(_translate("Form", "ADD ITEM"))
        self.view_inventory.setText(_translate("Form", "VIEW INVENTORY"))
        self.exit.setText(_translate("Form", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
