# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from models import session,sales
from PyQt5.QtWidgets import QMessageBox
import sales_dashboard
class Ui_Form(object):
    def __init__(self):
        # Create a QWidget instance to be used as the parent for file dialogs
        self.parent_widget = QtWidgets.QWidget()
    def viewSalesHistory(self):
        self.windows = QtWidgets.QMainWindow()
        self.ui = sales_dashboard.Ui_Form()
        self.ui.setupUi(self.windows)
        self.windows.show()
        
    def addSales(self):
        if self.amount.text() == '':
            QMessageBox.warning(self.parent_widget,'Amount Error','Amount must be a valid amount and not null')
        elif self.amount.text().isalpha():
            QMessageBox.warning(self.parent_widget,'Amount Error','Amount must be a valid amount and not words or letters')
        else:
            if self.date.text() == "":
                new_sales = sales(totals=float(self.amount.text()))
                session.add(new_sales)
                session.commit()
                QMessageBox.information(self.parent_widget,'Export successfull','Sales Data Has been Added to the database')
            elif not self.date.text() == '':
                new_sales = sales(amount=self.amount.text())
                session.add(new_sales)
                session.commit()
                QMessageBox.information(self.parent_widget,'Export successfull','Sales Data Has been Added to the database')
            
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        Form.setMaximumSize(1000,800)
        Form.setMinimumSize(1000,800)
        icon = QtGui.QIcon.fromTheme("k")
        Form.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1001, 111))
        self.widget.setStyleSheet("background-color: rgb(255, 51, 170);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(400, 10, 341, 51))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1001, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(390, 130, 251, 31))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 210, 251, 31))
        self.label_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setGeometry(QtCore.QRect(400, 199, 501, 61))
        self.title.setObjectName("title")
        self.title.setPlaceholderText('Not a must')
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(110, 311, 100, 31))
        self.label_4.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.amount = QtWidgets.QLineEdit(Form)
        self.amount.setGeometry(QtCore.QRect(400, 300, 501, 61))
        self.amount.setObjectName("amount")
        self.amount.setPlaceholderText('Must be filled with correct amount')
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(110, 421, 271, 31))
        self.label_5.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.date = QtWidgets.QLineEdit(Form)
        self.date.setGeometry(QtCore.QRect(400, 410, 501, 61))
        self.date.setText("")
        self.date.setObjectName("date")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(110, 571, 91, 31))
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(-10, 770, 1011, 31))
        self.widget_2.setStyleSheet("background-color: rgb(100, 233, 134);")
        self.widget_2.setObjectName("widget_2")
        self.add_sales = QtWidgets.QPushButton(Form)
        self.add_sales.setGeometry(QtCore.QRect(40, 660, 271, 81))
        self.add_sales.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.add_sales.setObjectName("add_sales")
        self.view_sales = QtWidgets.QPushButton(Form)
        self.view_sales.setGeometry(QtCore.QRect(410, 660, 271, 81))
        self.view_sales.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.view_sales.setObjectName("view_sales")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(770, 660, 161, 81))
        self.exit.setStyleSheet("background-color: rgb(250, 235, 215);")
        self.exit.setObjectName("exit")
        self.details = QtWidgets.QLineEdit(Form)
        self.details.setGeometry(QtCore.QRect(400, 570, 501, 61))
        self.details.setObjectName("details")
        self.details.setPlaceholderText("Not a must")
        self.view_sales.clicked.connect(self.viewSalesHistory)
        self.add_sales.clicked.connect(self.addSales)

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New Sales"))
        self.label.setText(_translate("Form", "NEW SALES"))
        self.label_2.setText(_translate("Form", "Fill In The Fields Below"))
        self.label_3.setText(_translate("Form", "Title:"))
        self.label_4.setText(_translate("Form", "Amount ksh:"))
        self.label_5.setText(_translate("Form", "Date of Sales:"))
        self.date.setPlaceholderText(_translate("Form", "Dont add date to set it to now"))
        self.label_6.setText(_translate("Form", "Details:"))
        self.add_sales.setText(_translate("Form", "ADD SALES"))
        self.view_sales.setText(_translate("Form", "VIEW SALES HISTORY"))
        self.exit.setText(_translate("Form", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
